In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
dataset = pd.read_csv('drive/My Drive/Colab Notebooks/preprocessedtrain.csv')

In [0]:
X = dataset.iloc[:, 0:10].values

In [0]:
Y = dataset.iloc[:, 11].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0, random_state = 0)

In [36]:
import xgboost
classifier = xgboost.XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [0]:
y_pred = classifier.predict(X)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y, y_pred)

In [39]:
print(cm)

[[105609     16   6080   1760   1961]
 [   390 219213     37   1422      0]
 [   995      6 303083     14    115]
 [   387    324    130 124208     45]
 [  2406      2    690    567  30540]]


In [0]:
testdataset = pd.read_csv('drive/My Drive/Colab Notebooks/preprocessedtest.csv')

In [0]:
X_test = testdataset.iloc[:, 0:10].values

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
df = pd.DataFrame(y_pred)
df.to_csv("drive/My Drive/test_labels.csv")